<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260416090803 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE booking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total_credits INT NOT NULL, status VARCHAR(16) DEFAULT \'confirmed\' NOT NULL, idempotency_key VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, event_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E00CEDDEA76ED395 ON booking (user_id)');
        $this->addSql('CREATE INDEX IDX_E00CEDDE71F7E88B ON booking (event_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_booking_idempotency_key ON booking (idempotency_key)');
        $this->addSql('CREATE TABLE booking_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, unit_base_price INT NOT NULL, unit_final_price INT NOT NULL, system_fee INT NOT NULL, booking_id INT NOT NULL, tier_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_78A07503301C60 ON booking_item (booking_id)');
        $this->addSql('CREATE INDEX IDX_78A0750A354F9DC ON booking_item (tier_id)');
        $this->addSql('CREATE TABLE e_ticket (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, qr_token VARCHAR(64) NOT NULL, file_path VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, booking_item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ED6E4E848D1177E ON e_ticket (booking_item_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_eticket_qr_token ON e_ticket (qr_token)');
        $this->addSql('CREATE TABLE event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, description TEXT NOT NULL, category VARCHAR(64) NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, timezone VARCHAR(64) DEFAULT \'UTC\' NOT NULL, is_online BOOLEAN DEFAULT false NOT NULL, venue_name VARCHAR(200) DEFAULT NULL, venue_address VARCHAR(255) DEFAULT NULL, status VARCHAR(16) DEFAULT \'draft\' NOT NULL, banner_path VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organizer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3BAE0AA7876C4DDA ON event (organizer_id)');
        $this->addSql('CREATE TABLE organizer_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, approval_status VARCHAR(16) DEFAULT \'pending\' NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C8661DC6A76ED395 ON organizer_profile (user_id)');
        $this->addSql('CREATE TABLE seat_reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, reserved_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(16) DEFAULT \'pending\' NOT NULL, user_id INT NOT NULL, tier_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6793F25FA76ED395 ON seat_reservation (user_id)');
        $this->addSql('CREATE INDEX IDX_6793F25FA354F9DC ON seat_reservation (tier_id)');
        $this->addSql('CREATE INDEX idx_reservation_expires_at ON seat_reservation (expires_at)');
        $this->addSql('CREATE TABLE ticket_tier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(64) NOT NULL, base_price INT NOT NULL, total_seats INT NOT NULL, sale_starts_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, sale_ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, version INT DEFAULT 1 NOT NULL, event_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_164582B271F7E88B ON ticket_tier (event_id)');
        $this->addSql('CREATE TABLE transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount INT NOT NULL, type VARCHAR(16) NOT NULL, reference VARCHAR(128) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_723705D1A76ED395 ON transaction (user_id)');
        $this->addSql('CREATE INDEX idx_transaction_user_created_at ON transaction (user_id, created_at)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, credit_balance INT DEFAULT 2000 NOT NULL, timezone VARCHAR(64) DEFAULT \'UTC\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking_item ADD CONSTRAINT FK_78A07503301C60 FOREIGN KEY (booking_id) REFERENCES booking (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking_item ADD CONSTRAINT FK_78A0750A354F9DC FOREIGN KEY (tier_id) REFERENCES ticket_tier (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE e_ticket ADD CONSTRAINT FK_ED6E4E848D1177E FOREIGN KEY (booking_item_id) REFERENCES booking_item (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7876C4DDA FOREIGN KEY (organizer_id) REFERENCES organizer_profile (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE organizer_profile ADD CONSTRAINT FK_C8661DC6A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE seat_reservation ADD CONSTRAINT FK_6793F25FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE seat_reservation ADD CONSTRAINT FK_6793F25FA354F9DC FOREIGN KEY (tier_id) REFERENCES ticket_tier (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket_tier ADD CONSTRAINT FK_164582B271F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDEA76ED395');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE71F7E88B');
        $this->addSql('ALTER TABLE booking_item DROP CONSTRAINT FK_78A07503301C60');
        $this->addSql('ALTER TABLE booking_item DROP CONSTRAINT FK_78A0750A354F9DC');
        $this->addSql('ALTER TABLE e_ticket DROP CONSTRAINT FK_ED6E4E848D1177E');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7876C4DDA');
        $this->addSql('ALTER TABLE organizer_profile DROP CONSTRAINT FK_C8661DC6A76ED395');
        $this->addSql('ALTER TABLE seat_reservation DROP CONSTRAINT FK_6793F25FA76ED395');
        $this->addSql('ALTER TABLE seat_reservation DROP CONSTRAINT FK_6793F25FA354F9DC');
        $this->addSql('ALTER TABLE ticket_tier DROP CONSTRAINT FK_164582B271F7E88B');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D1A76ED395');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE booking_item');
        $this->addSql('DROP TABLE e_ticket');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE organizer_profile');
        $this->addSql('DROP TABLE seat_reservation');
        $this->addSql('DROP TABLE ticket_tier');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
